### ISSUE TITLE
No tab selection like in orginal fzf to select multiple fiels using  tab

### ISSUE THREAD

**Issue by RVSNS** [patrickf3139/fzf.fish#56]

**Comment by patrickf3139** [comment]
Hi @RVSNS, that was an intentional decision. While Jethro Kuan's fzf does have tab completion, it is buggy and hard to maintain. See all the problems about it here https://github.com/jethrokuan/fzf/issues?q=is%3Aissue+tab. I will consider implementing it later if there is more interest. Sorry about that.
